services:
  db:
    container_name: 'postgresql'
    image: 'postgres'
    ports: 
      - '5433:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fodder

volumes: 
  data: {}